<a href="https://colab.research.google.com/github/NSF-DARSE/YolktoFeed/blob/main/JupyterNotebook/liverHEDI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
import sys
import numpy as np

In [50]:
path = "/content/drive/Shareddrives/NSF-SCIPE-DARSE/Research Software Engineers (RSE)/Abhin/Projects/Carl Schmidt"
sys.path.append(path)

In [51]:
df_base = pd.read_csv(path+"/Liver_HEIDI_complete_ensembl_symbol.csv")

In [52]:
print("Number of genes: ", df_base.shape[0])

# finding last row with valid gene symbol
gene_list_last_index = (df_base["Gene Symbol"] == "-").idxmax()

print("Number of nan's: ", df_base.iloc[:,2:].apply(pd.to_numeric, errors='coerce').isna().sum().sum())

Number of genes:  24869
Number of nan's:  0

In [53]:
#truncating till that row
df_trunk = df_base.iloc[:gene_list_last_index]
df_trunk = df_trunk.drop(columns=["Ensembl Gene ID"])
df_trunk = df_trunk.set_index("Gene Symbol")
df_trunk

,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,1671_summed_TPM_4,1672_summed_TPM_4,1673_summed_TPM_4,...,1735_summed_TPM_20,1736_summed_TPM_20,1742_summed_TPM_20,1743_summed_TPM_20,1744_summed_TPM_20,1745_summed_TPM_20,1746_summed_TPM_20,1747_summed_TPM_20,1748_summed_TPM_20,1749_summed_TPM_20
Gene Symbol,,,,,,,,,,,,,,,,,,,,,
ZZZ3,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,3.031530,2.721210,3.941250,...,0.970587,1.66351,1.636580,2.459220,4.893390,2.489600,3.19717,1.468440,2.091560,0.187683
ZYX,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,27.918300,34.052300,57.311000,...,13.140900,24.40290,25.381200,28.666700,34.741500,22.507700,29.35630,25.152600,34.865400,12.079700
ZXDC,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,2.161720,2.230180,4.596810,...,0.945374,1.22140,1.271560,2.263090,2.274030,1.651320,2.59244,2.715000,2.818080,0.710741
ZW10,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,6.426870,5.543910,8.634280,...,2.026740,3.13406,4.484710,5.776710,8.311750,4.391920,6.41727,4.316070,5.518810,1.944010
ZUFSP,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,3.496990,2.421560,2.140630,...,2.675900,1.74104,1.222440,3.358820,3.351070,2.998520,2.41147,1.658470,2.003540,0.645755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A4GALT,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,0.067055,0.061017,0.105077,...,0.172556,0.00000,0.131267,0.230045,0.594857,0.254973,0.22188,0.201177,0.596807,0.095215
A2ML4,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,492.456000,1092.230000,723.640000,...,211.638000,641.81200,604.835000,1026.430000,1004.110000,480.376000,1000.24000,778.891000,1191.370000,394.840000
A2ML2,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,169.966000,165.030000,182.840000,...,130.653000,193.07000,301.891000,275.247000,395.356000,316.083000,156.38600,128.938000,186.548000,81.135700
A1CF,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,104.168000,76.200500,114.381000,...,15.616700,37.06100,14.489100,36.690700,35.393500,20.619700,48.11020,28.213400,27.961700,4.667240
2KTGRL,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,27.385400,22.523600,17.135500,...,19.211000,19.48700,10.104500,23.347600,30.215600,21.947100,20.14000,18.413500,10.618500,4.852390

In [54]:
df_trunk.insert(0, "avg", df_trunk.iloc[:, :].sum(axis=1)/(df_trunk.shape[1]-1))
df_trunk.insert(1, "sigma", df_trunk.iloc[:,:].var(axis=1))
df_trunk.insert(2, "max", df_trunk.iloc[:,:].max(axis=1))
df_trunk

,avg,sigma,max,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,...,1735_summed_TPM_20,1736_summed_TPM_20,1742_summed_TPM_20,1743_summed_TPM_20,1744_summed_TPM_20,1745_summed_TPM_20,1746_summed_TPM_20,1747_summed_TPM_20,1748_summed_TPM_20,1749_summed_TPM_20
Gene Symbol,,,,,,,,,,,,,,,,,,,,,
ZZZ3,3.656696,4.078288,10.133400,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,...,0.970587,1.66351,1.636580,2.459220,4.893390,2.489600,3.19717,1.468440,2.091560,0.187683
ZYX,29.255917,92.037798,92.037798,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,...,13.140900,24.40290,25.381200,28.666700,34.741500,22.507700,29.35630,25.152600,34.865400,12.079700
ZXDC,2.328608,1.159859,5.924810,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,...,0.945374,1.22140,1.271560,2.263090,2.274030,1.651320,2.59244,2.715000,2.818080,0.710741
ZW10,6.511227,8.820368,14.179500,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,...,2.026740,3.13406,4.484710,5.776710,8.311750,4.391920,6.41727,4.316070,5.518810,1.944010
ZUFSP,3.981787,5.608131,12.019500,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,...,2.675900,1.74104,1.222440,3.358820,3.351070,2.998520,2.41147,1.658470,2.003540,0.645755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A4GALT,0.298291,0.036620,0.882417,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,...,0.172556,0.00000,0.131267,0.230045,0.594857,0.254973,0.22188,0.201177,0.596807,0.095215
A2ML4,669.944670,150677.844053,150677.844053,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,...,211.638000,641.81200,604.835000,1026.430000,1004.110000,480.376000,1000.24000,778.891000,1191.370000,394.840000
A2ML2,212.732710,8557.606247,8557.606247,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,...,130.653000,193.07000,301.891000,275.247000,395.356000,316.083000,156.38600,128.938000,186.548000,81.135700
A1CF,52.886517,1164.266745,1164.266745,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,...,15.616700,37.06100,14.489100,36.690700,35.393500,20.619700,48.11020,28.213400,27.961700,4.667240
2KTGRL,22.763002,78.757353,78.757353,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,...,19.211000,19.48700,10.104500,23.347600,30.215600,21.947100,20.14000,18.413500,10.618500,4.852390

In [55]:
#df_trunk = df_trunk[(df_trunk.loc[:,'avg'] > 1e-1)]
#df_trunk

In [56]:
#df_trunk = df_trunk[(df_trunk.loc[:,'sigma'] > 1e-1)]
#df_trunk

In [57]:
#droping day 6
df_trunk = df_trunk.loc[:, ~df_trunk.columns.str.endswith('_6')]
df_trunk

,avg,sigma,max,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,...,1735_summed_TPM_20,1736_summed_TPM_20,1742_summed_TPM_20,1743_summed_TPM_20,1744_summed_TPM_20,1745_summed_TPM_20,1746_summed_TPM_20,1747_summed_TPM_20,1748_summed_TPM_20,1749_summed_TPM_20
Gene Symbol,,,,,,,,,,,,,,,,,,,,,
ZZZ3,3.656696,4.078288,10.133400,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,...,0.970587,1.66351,1.636580,2.459220,4.893390,2.489600,3.19717,1.468440,2.091560,0.187683
ZYX,29.255917,92.037798,92.037798,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,...,13.140900,24.40290,25.381200,28.666700,34.741500,22.507700,29.35630,25.152600,34.865400,12.079700
ZXDC,2.328608,1.159859,5.924810,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,...,0.945374,1.22140,1.271560,2.263090,2.274030,1.651320,2.59244,2.715000,2.818080,0.710741
ZW10,6.511227,8.820368,14.179500,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,...,2.026740,3.13406,4.484710,5.776710,8.311750,4.391920,6.41727,4.316070,5.518810,1.944010
ZUFSP,3.981787,5.608131,12.019500,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,...,2.675900,1.74104,1.222440,3.358820,3.351070,2.998520,2.41147,1.658470,2.003540,0.645755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A4GALT,0.298291,0.036620,0.882417,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,...,0.172556,0.00000,0.131267,0.230045,0.594857,0.254973,0.22188,0.201177,0.596807,0.095215
A2ML4,669.944670,150677.844053,150677.844053,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,...,211.638000,641.81200,604.835000,1026.430000,1004.110000,480.376000,1000.24000,778.891000,1191.370000,394.840000
A2ML2,212.732710,8557.606247,8557.606247,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,...,130.653000,193.07000,301.891000,275.247000,395.356000,316.083000,156.38600,128.938000,186.548000,81.135700
A1CF,52.886517,1164.266745,1164.266745,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,...,15.616700,37.06100,14.489100,36.690700,35.393500,20.619700,48.11020,28.213400,27.961700,4.667240
2KTGRL,22.763002,78.757353,78.757353,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,...,19.211000,19.48700,10.104500,23.347600,30.215600,21.947100,20.14000,18.413500,10.618500,4.852390

In [58]:
meta_cols = ['avg', 'sigma', 'max']
expr_cols = [c for c in df_trunk.columns if c not in meta_cols]

sample_meta = pd.DataFrame({'Sample': expr_cols})
sample_meta['Day'] = sample_meta['Sample'].str.extract(r'_(\d+)$').astype(int)
sample_meta

                Sample  Day
0    1650_summed_TPM_4    4
1    1651_summed_TPM_4    4
2    1653_summed_TPM_4    4
3    1654_summed_TPM_4    4
4    1655_summed_TPM_4    4
..                 ...  ...
89  1745_summed_TPM_20   20
90  1746_summed_TPM_20   20
91  1747_summed_TPM_20   20
92  1748_summed_TPM_20   20
93  1749_summed_TPM_20   20

[94 rows x 2 columns]

In [59]:
DAYS = sorted(sample_meta['Day'].unique().tolist())
from collections import Counter
Counter(sample_meta['Day'].tolist())

Counter({4: 11, 8: 12, 10: 12, 12: 12, 14: 11, 16: 12, 18: 12, 20: 12})

## PCA Analysis

In [65]:
expr = df_trunk[expr_cols].copy()
expr = expr.T
expr

Gene Symbol,ZZZ3,ZYX,ZXDC,ZW10,ZUFSP,ZSWIM8,ZSWIM7,ZSWIM6,ZSWIM5,ZRSR2,...,AADACL4L1,AADAC,AACS,AAAS,A4GNT,A4GALT,A2ML4,A2ML2,A1CF,2KTGRL
1650_summed_TPM_4,2.148670,24.3662,2.032480,4.83476,3.170700,1.675780,6.17340,0.569296,2.178820,11.91600,...,0.0,41.0872,66.61410,10.76550,0.000000,0.074452,243.909,247.3320,22.04060,18.36280
1651_summed_TPM_4,4.204060,32.5692,2.471470,7.15083,2.908370,2.133430,6.60532,0.910666,1.761570,10.26490,...,0.0,83.8479,98.10680,6.66460,0.000000,0.156464,340.262,182.9510,55.03820,23.62360
1653_summed_TPM_4,3.609380,31.2539,1.543100,5.56367,2.354820,1.880430,4.91934,0.516069,1.619710,12.14410,...,0.0,43.4198,66.61370,9.98579,0.000000,0.029587,289.809,172.5010,26.66190,27.99770
1654_summed_TPM_4,6.677230,37.8472,3.037720,10.11710,3.346660,3.231300,5.27499,1.583670,3.911480,15.50520,...,0.0,138.2240,30.22150,15.87110,0.000000,0.139465,584.728,183.1290,96.15840,25.47570
1655_summed_TPM_4,3.849120,37.6928,1.771860,5.90561,2.564770,3.305450,6.09677,0.951165,2.540930,11.55160,...,0.0,64.4517,108.17100,15.18720,0.000000,0.190539,281.682,118.8260,26.07880,20.56600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745_summed_TPM_20,2.489600,22.5077,1.651320,4.39192,2.998520,1.015740,7.88132,0.417013,2.030230,8.27425,...,0.0,44.2974,33.32140,9.05072,0.164345,0.254973,480.376,316.0830,20.61970,21.94710
1746_summed_TPM_20,3.197170,29.3563,2.592440,6.41727,2.411470,4.452720,7.54821,0.510760,2.268500,7.97976,...,0.0,71.3296,21.35240,12.46240,0.000000,0.221880,1000.240,156.3860,48.11020,20.14000
1747_summed_TPM_20,1.468440,25.1526,2.715000,4.31607,1.658470,2.655280,7.65566,0.312879,2.575800,8.69635,...,0.0,69.2337,9.64844,13.40070,0.116005,0.201177,778.891,128.9380,28.21340,18.41350
1748_summed_TPM_20,2.091560,34.8654,2.818080,5.51881,2.003540,5.151000,9.14231,0.516501,2.912040,6.73500,...,0.0,77.0281,24.43640,13.32870,0.096097,0.596807,1191.370,186.5480,27.96170,10.61850
1749_summed_TPM_20,0.187683,12.0797,0.710741,1.94401,0.645755,0.404928,3.80336,0.125933,0.800351,3.90909,...,0.0,13.0031,2.24166,12.08650,0.000000,0.095215,394.840,81.1357,4.66724,4.85239

In [66]:
genes_to_keep = expr.columns[expr.sum(axis=0) >= 10]
expr = expr[genes_to_keep]
expr

Gene Symbol,ZZZ3,ZYX,ZXDC,ZW10,ZUFSP,ZSWIM8,ZSWIM7,ZSWIM6,ZSWIM5,ZRSR2,...,AAGAB,AADAT,AADAC,AACS,AAAS,A4GALT,A2ML4,A2ML2,A1CF,2KTGRL
1650_summed_TPM_4,2.148670,24.3662,2.032480,4.83476,3.170700,1.675780,6.17340,0.569296,2.178820,11.91600,...,3.32588,36.80990,41.0872,66.61410,10.76550,0.074452,243.909,247.3320,22.04060,18.36280
1651_summed_TPM_4,4.204060,32.5692,2.471470,7.15083,2.908370,2.133430,6.60532,0.910666,1.761570,10.26490,...,8.56948,26.28900,83.8479,98.10680,6.66460,0.156464,340.262,182.9510,55.03820,23.62360
1653_summed_TPM_4,3.609380,31.2539,1.543100,5.56367,2.354820,1.880430,4.91934,0.516069,1.619710,12.14410,...,6.83136,23.10730,43.4198,66.61370,9.98579,0.029587,289.809,172.5010,26.66190,27.99770
1654_summed_TPM_4,6.677230,37.8472,3.037720,10.11710,3.346660,3.231300,5.27499,1.583670,3.911480,15.50520,...,13.41280,31.93800,138.2240,30.22150,15.87110,0.139465,584.728,183.1290,96.15840,25.47570
1655_summed_TPM_4,3.849120,37.6928,1.771860,5.90561,2.564770,3.305450,6.09677,0.951165,2.540930,11.55160,...,5.56149,29.24950,64.4517,108.17100,15.18720,0.190539,281.682,118.8260,26.07880,20.56600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745_summed_TPM_20,2.489600,22.5077,1.651320,4.39192,2.998520,1.015740,7.88132,0.417013,2.030230,8.27425,...,3.24968,26.55960,44.2974,33.32140,9.05072,0.254973,480.376,316.0830,20.61970,21.94710
1746_summed_TPM_20,3.197170,29.3563,2.592440,6.41727,2.411470,4.452720,7.54821,0.510760,2.268500,7.97976,...,7.09506,22.56570,71.3296,21.35240,12.46240,0.221880,1000.240,156.3860,48.11020,20.14000
1747_summed_TPM_20,1.468440,25.1526,2.715000,4.31607,1.658470,2.655280,7.65566,0.312879,2.575800,8.69635,...,4.95184,13.52870,69.2337,9.64844,13.40070,0.201177,778.891,128.9380,28.21340,18.41350
1748_summed_TPM_20,2.091560,34.8654,2.818080,5.51881,2.003540,5.151000,9.14231,0.516501,2.912040,6.73500,...,6.09859,13.88040,77.0281,24.43640,13.32870,0.596807,1191.370,186.5480,27.96170,10.61850
1749_summed_TPM_20,0.187683,12.0797,0.710741,1.94401,0.645755,0.404928,3.80336,0.125933,0.800351,3.90909,...,1.52960,6.74431,13.0031,2.24166,12.08650,0.095215,394.840,81.1357,4.66724,4.85239

In [67]:
log_expr_vals = np.log2(expr.values + 1)
log_expr = pd.DataFrame(log_expr_vals, index=expr.index, columns=expr.columns)
log_expr

Gene Symbol,ZZZ3,ZYX,ZXDC,ZW10,ZUFSP,ZSWIM8,ZSWIM7,ZSWIM6,ZSWIM5,ZRSR2,...,AAGAB,AADAT,AADAC,AACS,AAAS,A4GALT,A2ML4,A2ML2,A1CF,2KTGRL
1650_summed_TPM_4,1.654743,4.664836,1.600498,2.544673,2.060290,1.419960,2.842657,0.650117,1.668491,3.691087,...,2.112994,5.240692,5.395310,6.079252,3.556491,0.103601,7.936102,7.956126,4.526106,4.275216
1651_summed_TPM_4,2.379638,5.069066,1.795547,3.026947,1.966567,1.647743,2.927009,0.934076,1.465489,3.493763,...,3.258441,4.770248,6.406807,6.630912,2.938211,0.209720,8.414736,7.523178,5.808339,4.621970
1653_summed_TPM_4,2.204573,5.011402,1.346588,2.714503,1.746235,1.526284,2.565436,0.600335,1.389407,3.716343,...,2.969263,4.591398,5.473131,6.079244,3.457567,0.042066,8.183928,7.438800,4.789828,4.857867
1654_summed_TPM_4,2.940586,5.279739,2.013541,3.474709,2.119907,2.081101,2.649613,1.369422,2.296158,4.044849,...,3.849279,5.041681,7.121264,4.964468,4.076482,0.188357,9.194087,7.524573,6.602267,4.726597
1655_summed_TPM_4,2.277723,5.273993,1.470854,2.787769,1.833809,2.106164,2.827163,0.964336,1.824128,3.649799,...,2.714023,4.918839,6.032359,6.770446,4.016782,0.251615,8.143036,6.904797,4.759092,4.430687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745_summed_TPM_20,1.803062,4.555061,1.406711,2.430799,1.999466,1.011310,3.150774,0.502853,1.599427,3.213231,...,2.087354,4.784483,5.501356,5.101036,3.329227,0.327656,8.911020,8.308717,4.434275,4.520240
1746_summed_TPM_20,2.069417,4.923924,1.844964,2.890888,1.770394,2.446976,3.095622,0.595274,1.708629,3.166677,...,3.017042,4.558617,6.176514,4.482358,3.750864,0.289103,9.967572,7.298163,5.617951,4.401903
1747_summed_TPM_20,1.303600,4.708882,1.893362,2.410360,1.410596,1.869982,3.113644,0.392734,1.838266,3.277442,...,2.573336,3.860834,6.134092,3.412570,3.848067,0.264449,9.607129,7.021680,4.868558,4.278988
1748_summed_TPM_20,1.628335,5.164521,1.932847,2.704609,1.586664,2.620821,3.342314,0.600746,1.967921,2.951401,...,2.827532,3.895341,6.285922,4.668823,3.840836,0.675190,10.219616,7.551116,4.856074,3.538352
1749_summed_TPM_20,0.248150,3.709258,0.774621,1.557783,0.718750,0.490496,2.264044,0.171121,0.848278,2.295456,...,1.338909,2.953137,3.807674,1.696733,3.710007,0.131214,8.628774,6.359938,2.502646,2.549026

In [68]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X_t        = log_expr.values.astype(float)
X_t_scaled = StandardScaler().fit_transform(X_t)

pca_t = PCA(n_components=10, random_state=42)
Xpca  = pca_t.fit_transform(X_t_scaled)

print(f"  PC1 explains: {pca_t.explained_variance_ratio_[0]*100:.1f}% of variance")
print(f"  PC2 explains: {pca_t.explained_variance_ratio_[1]*100:.1f}% of variance")
print(f"  PC3 explains: {pca_t.explained_variance_ratio_[2]*100:.1f}% of variance")
print(f"  PC4 explains: {pca_t.explained_variance_ratio_[3]*100:.1f}% of variance")
print(f"  Xpca shape  : {Xpca.shape}")

  PC1 explains: 45.0% of variance
  PC2 explains: 8.7% of variance
  PC3 explains: 5.1% of variance
  PC4 explains: 4.2% of variance
  Xpca shape  : (94, 10)